server:
  port: 8082
  servlet:
    context-path: /customer-service

spring:
  application:
    name: customer-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
