server:
  port: 8083
  servlet:
    context-path: /product-service

spring:
  application:
    name: product-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
